#!/bin/bash

file="/sys/class/backlight/acpi_video0/brightness"
currentval=$(cat $file)
newval=${1:-$currentval}

# -i = increment
# -d = decrement
if [[ $# == 2 ]]; then
    if [[ $1 == "-i" ]]; then
	newval=$(( currentval + $2 ))
    elif [[ $1 == "-d" ]]; then
	newval=$(( currentval - $2 ))
    fi   
fi

if [[ $newval -lt 0 ]]; then
    newval=0
elif [[ $newval -gt 95 ]]; then
    newval=95
fi

echo $newval > $file
