#!/bin/bash

current=$([[ $(grep vanillalight ~/.Xdefaults) != "" ]] && echo light || echo dark)

if [[ $current == "light" ]]; then
    substitution="s/vanillalight/vanilladark/"
    statusarg="dark"
else
    substitution="s/vanilladark/vanillalight/"
fi

sed -i --follow-symlinks "$substitution" ~/.Xdefaults
sed -i "$substitution" ~/.config/wmfs/wmfsrc

colorfile=$(cat ~/.Xdefaults | grep "\.colors" | cut -d '"' -f2)
bgcolor=$(sed -n "s/\*color0: *//p" "$colorfile")

hsetroot -solid "$bgcolor" &

killall conky
nohup statusbar "$statusarg" > /dev/null 2>&1 &

wmfs -c reload
