#!/usr/bin/env python

import curses
import curses.textpad

class ScrollWindow:
    def __init__(self, parent, HISTORY=None):
        self.parent = parent
        self.BEGY, self.BEGX = parent.getbegyx()
        self.MAXY, self.MAXX = parent.getmaxyx()

        if HISTORY < self.MAXY or HISTORY is None:
            self.HISTORY = self.MAXY
        else:
            self.HISTORY = HISTORY

        self.pad = curses.newpad(self.HISTORY, self.MAXX)
        self.pad.scrollok(True)
        self.position = 0
        
    def refresh(self):
        self.pad.refresh(self.position, 0, self.BEGY, self.BEGX, self.MAXY - 1,
                         self.MAXX)

    def addstr(self, string):
        self.pad.addstr(string)

    def erase(self):
        self.pad.erase()
        self.position = 0

    def scroll(self, lines=1):
        y, x = self.pad.getyx()
        if self.position + lines < 0:
            self.position = 0
        elif self.position + lines + self.MAXY > y:
            self.position = y - self.MAXY
        else:
            self.position += lines

    def home(self):
        if self.position != 0:
            self.position = 0

    def end(self):
        y, x = self.pad.getyx()
        if y > self.MAXY:
            self.position = y - self.MAXY

def main(stdscr):
    curses.use_default_colors()
    history = 1000
    
    y, x = stdscr.getmaxyx()

    content = stdscr.subwin(y - 1, x, 0, 0)
    pad = ScrollWindow(content, history)
    
    global pad

    bufwin = stdscr.subwin(1, x, y - 1, 0)    
    textbox = curses.textpad.Textbox(bufwin)
    textbox.stripspaces = True

    for i in range (0, 10):
        pad.addstr(str(i) + '\n')

#    stdscr.refresh() WHY?
    pad.refresh()
    while True:
        input = textbox.edit(handle)
        bufwin.erase()
        pad.addstr('> ' + input + '\n')
        pad.end()
        pad.refresh()

def handle(ch):
    if ch == curses.KEY_UP:
        pad.scroll(-1)
        pad.refresh()
    elif ch == curses.KEY_DOWN:
        pad.scroll(1)
        pad.refresh()
    elif ch == curses.KEY_PPAGE:
        pad.scroll(-10)
        pad.refresh()
    elif ch == curses.KEY_NPAGE:
        pad.scroll(10)
        pad.refresh()
    elif ch == curses.KEY_HOME:
        pad.home()
        pad.refresh()
    elif ch == curses.KEY_END:
        pad.end()
        pad.refresh()
    else:
        return ch
    
curses.wrapper(main)
